### ISSUE TITLE
Default username and password

### ISSUE THREAD

**Issue by dumtux** [EchoHeim/Allwinner-H616#1]
Thanks for the great work.
What is the default username and password?
And how can I modify default username and password before building?

**Comment by EchoHeim** [comment]
In the `scripts/main.sh` file:

![image](https://user-images.githubusercontent.com/26021085/202976737-ddd21c70-f875-42d7-9397-771e35b0266f.png)

**Comment by dumtux** [comment]
Thank you.
It worked.
