### ISSUE TITLE
sunxi-gmac 5030000.ethernet eth0: No PHY found!

### ISSUE THREAD

**Issue by Im670** [EchoHeim/Allwinner-H616#4]
root@BTT-CB1:/# ifconfig eth0 up
SIOCSIFFLAGS: Invalid argument
root@BTT-CB1:/# dmesg -c        
[ 3380.611988] mii_bus 5030000.ethernet-0 register success!
[ 3380.899302] sunxi-gmac 5030000.ethernet eth0: No PHY found!
[ 3380.902573] sunxi-gmac 5030000.ethernet eth0: phy init again...
[ 3380.903123] mii_bus 5030000.ethernet-0 register success!
[ 3381.193546] sunxi-gmac 5030000.ethernet eth0: No PHY found!
[ 3381.197490] sunxi-gmac 5030000.ethernet eth0: phy init failed

**Comment by EchoHeim** [comment]
The log message indicates that the gmac driver has been loaded successfully.
NO PHY found.
I would like to know which soc master you have, because according to the official Allwinner manual, the internal gmac1 is connected to different NICs for different socs, maybe AC100/200/300.

**Comment by Im670** [comment]
NOTICE:  BL31: Detected Allwinner H616 SoC (1823)   

is this helpful ?

**Comment by Im670** [comment]
@EchoHeim  thanks ! I found the problem , my H616 version is ba , I should used h616 new version (bb With New ac300) !
